# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.srcs/sources_1/bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5.xci
# IP: The module: 'TimeCard_auto_cc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_auto_cc_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_auto_cc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.srcs/sources_1/bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5.xci
# IP: The module: 'TimeCard_auto_cc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_auto_cc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_auto_cc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
