# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/Constraints/PinoutConstraint.xdc

# XDC: C:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/Constraints/TimingConstraint.sdc

# XDC: C:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/Constraints/UpdateImageConstraint.xdc

# Block Designs: bd/TimeCard/TimeCard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard || ORIG_REF_NAME==TimeCard} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_BufgMux_IPI_0_0/TimeCard_BufgMux_IPI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_BufgMux_IPI_0_0 || ORIG_REF_NAME==TimeCard_BufgMux_IPI_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_BufgMux_IPI_1_0/TimeCard_BufgMux_IPI_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_BufgMux_IPI_1_0 || ORIG_REF_NAME==TimeCard_BufgMux_IPI_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_BufgMux_IPI_2_0/TimeCard_BufgMux_IPI_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_BufgMux_IPI_2_0 || ORIG_REF_NAME==TimeCard_BufgMux_IPI_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_AdjustableClock_0_0/TimeCard_TC_AdjustableClock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_AdjustableClock_0_0 || ORIG_REF_NAME==TimeCard_TC_AdjustableClock_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_ClockDetector_0_0/TimeCard_TC_ClockDetector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_ClockDetector_0_0 || ORIG_REF_NAME==TimeCard_TC_ClockDetector_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_ConfMaster_0_0/TimeCard_TC_ConfMaster_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_ConfMaster_0_0 || ORIG_REF_NAME==TimeCard_TC_ConfMaster_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_CoreList_0_0/TimeCard_TC_CoreList_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_CoreList_0_0 || ORIG_REF_NAME==TimeCard_TC_CoreList_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_DummyAxiSlave_0_0/TimeCard_TC_DummyAxiSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_DummyAxiSlave_0_0 || ORIG_REF_NAME==TimeCard_TC_DummyAxiSlave_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_DummyAxiSlave_1_0/TimeCard_TC_DummyAxiSlave_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_DummyAxiSlave_1_0 || ORIG_REF_NAME==TimeCard_TC_DummyAxiSlave_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_DummyAxiSlave_2_0/TimeCard_TC_DummyAxiSlave_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_DummyAxiSlave_2_0 || ORIG_REF_NAME==TimeCard_TC_DummyAxiSlave_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_DummyAxiSlave_3_0/TimeCard_TC_DummyAxiSlave_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_DummyAxiSlave_3_0 || ORIG_REF_NAME==TimeCard_TC_DummyAxiSlave_3_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_DummyAxiSlave_4_0/TimeCard_TC_DummyAxiSlave_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_DummyAxiSlave_4_0 || ORIG_REF_NAME==TimeCard_TC_DummyAxiSlave_4_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_FpgaVersion_0_0/TimeCard_TC_FpgaVersion_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_FpgaVersion_0_0 || ORIG_REF_NAME==TimeCard_TC_FpgaVersion_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_FrequencyCounter_1_0/TimeCard_TC_FrequencyCounter_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_FrequencyCounter_1_0 || ORIG_REF_NAME==TimeCard_TC_FrequencyCounter_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_FrequencyCounter_2_0/TimeCard_TC_FrequencyCounter_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_FrequencyCounter_2_0 || ORIG_REF_NAME==TimeCard_TC_FrequencyCounter_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_FrequencyCounter_3_0/TimeCard_TC_FrequencyCounter_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_FrequencyCounter_3_0 || ORIG_REF_NAME==TimeCard_TC_FrequencyCounter_3_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_FrequencyCounter_4_0/TimeCard_TC_FrequencyCounter_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_FrequencyCounter_4_0 || ORIG_REF_NAME==TimeCard_TC_FrequencyCounter_4_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_MsiIrq_0_0/TimeCard_TC_MsiIrq_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_MsiIrq_0_0 || ORIG_REF_NAME==TimeCard_TC_MsiIrq_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_PpsGenerator_0_0/TimeCard_TC_PpsGenerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_PpsGenerator_0_0 || ORIG_REF_NAME==TimeCard_TC_PpsGenerator_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_PpsSlave_0_0/TimeCard_TC_PpsSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_PpsSlave_0_0 || ORIG_REF_NAME==TimeCard_TC_PpsSlave_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_PpsSourceSelector_0_0/TimeCard_TC_PpsSourceSelector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_PpsSourceSelector_0_0 || ORIG_REF_NAME==TimeCard_TC_PpsSourceSelector_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_PpsSourceSelector_1_0/TimeCard_TC_PpsSourceSelector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_PpsSourceSelector_1_0 || ORIG_REF_NAME==TimeCard_TC_PpsSourceSelector_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_SignalGenerator_1_0/TimeCard_TC_SignalGenerator_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_SignalGenerator_1_0 || ORIG_REF_NAME==TimeCard_TC_SignalGenerator_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_SignalGenerator_2_0/TimeCard_TC_SignalGenerator_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_SignalGenerator_2_0 || ORIG_REF_NAME==TimeCard_TC_SignalGenerator_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_SignalGenerator_3_0/TimeCard_TC_SignalGenerator_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_SignalGenerator_3_0 || ORIG_REF_NAME==TimeCard_TC_SignalGenerator_3_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_SignalGenerator_4_0/TimeCard_TC_SignalGenerator_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_SignalGenerator_4_0 || ORIG_REF_NAME==TimeCard_TC_SignalGenerator_4_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_SmaSelector_0_0/TimeCard_TC_SmaSelector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_SmaSelector_0_0 || ORIG_REF_NAME==TimeCard_TC_SmaSelector_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_Timestamper_1_0/TimeCard_TC_Timestamper_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_Timestamper_1_0 || ORIG_REF_NAME==TimeCard_TC_Timestamper_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_Timestamper_2_0/TimeCard_TC_Timestamper_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_Timestamper_2_0 || ORIG_REF_NAME==TimeCard_TC_Timestamper_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_Timestamper_3_0/TimeCard_TC_Timestamper_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_Timestamper_3_0 || ORIG_REF_NAME==TimeCard_TC_Timestamper_3_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_Timestamper_4_0/TimeCard_TC_Timestamper_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_Timestamper_4_0 || ORIG_REF_NAME==TimeCard_TC_Timestamper_4_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_Timestamper_FpgaPps_0/TimeCard_TC_Timestamper_FpgaPps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_Timestamper_FpgaPps_0 || ORIG_REF_NAME==TimeCard_TC_Timestamper_FpgaPps_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_Timestamper_Gnss1Pps_0/TimeCard_TC_Timestamper_Gnss1Pps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_Timestamper_Gnss1Pps_0 || ORIG_REF_NAME==TimeCard_TC_Timestamper_Gnss1Pps_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_TC_TodSlave_0_0/TimeCard_TC_TodSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_TC_TodSlave_0_0 || ORIG_REF_NAME==TimeCard_TC_TodSlave_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_gpio_ext_0/TimeCard_axi_gpio_ext_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_gpio_ext_0 || ORIG_REF_NAME==TimeCard_axi_gpio_ext_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_gpio_gnss_mac_0/TimeCard_axi_gpio_gnss_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_gpio_gnss_mac_0 || ORIG_REF_NAME==TimeCard_axi_gpio_gnss_mac_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_gpio_rgb_0/TimeCard_axi_gpio_rgb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_gpio_rgb_0 || ORIG_REF_NAME==TimeCard_axi_gpio_rgb_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_hwicap_0_0/TimeCard_axi_hwicap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_hwicap_0_0 || ORIG_REF_NAME==TimeCard_axi_hwicap_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_iic_0/TimeCard_axi_iic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_iic_0 || ORIG_REF_NAME==TimeCard_axi_iic_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_iic_eeprom_0/TimeCard_axi_iic_eeprom_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_iic_eeprom_0 || ORIG_REF_NAME==TimeCard_axi_iic_eeprom_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_iic_rgb_0/TimeCard_axi_iic_rgb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_iic_rgb_0 || ORIG_REF_NAME==TimeCard_axi_iic_rgb_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xbar_0/TimeCard_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xbar_0 || ORIG_REF_NAME==TimeCard_xbar_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_interconnect_0_0/TimeCard_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_interconnect_0_0 || ORIG_REF_NAME==TimeCard_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xbar_1/TimeCard_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xbar_1 || ORIG_REF_NAME==TimeCard_xbar_1} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_interconnect_GPIO_0/TimeCard_axi_interconnect_GPIO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_interconnect_GPIO_0 || ORIG_REF_NAME==TimeCard_axi_interconnect_GPIO_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xbar_2/TimeCard_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xbar_2 || ORIG_REF_NAME==TimeCard_xbar_2} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_interconnect_IIC_0/TimeCard_axi_interconnect_IIC_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_interconnect_IIC_0 || ORIG_REF_NAME==TimeCard_axi_interconnect_IIC_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xbar_3/TimeCard_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xbar_3 || ORIG_REF_NAME==TimeCard_xbar_3} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_interconnect_timecard_0/TimeCard_axi_interconnect_timecard_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_interconnect_timecard_0 || ORIG_REF_NAME==TimeCard_axi_interconnect_timecard_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_pcie_0_0/TimeCard_axi_pcie_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_pcie_0_0 || ORIG_REF_NAME==TimeCard_axi_pcie_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_quad_spi_flash_0/TimeCard_axi_quad_spi_flash_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_quad_spi_flash_0 || ORIG_REF_NAME==TimeCard_axi_quad_spi_flash_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_uart16550_ext_0 || ORIG_REF_NAME==TimeCard_axi_uart16550_ext_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_uart16550_gnss1_0/TimeCard_axi_uart16550_gnss1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_uart16550_gnss1_0 || ORIG_REF_NAME==TimeCard_axi_uart16550_gnss1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_uart16550_gnss2_0/TimeCard_axi_uart16550_gnss2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_uart16550_gnss2_0 || ORIG_REF_NAME==TimeCard_axi_uart16550_gnss2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_uart16550_mac_0/TimeCard_axi_uart16550_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_uart16550_mac_0 || ORIG_REF_NAME==TimeCard_axi_uart16550_mac_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_axi_uart16550_reserved_0/TimeCard_axi_uart16550_reserved_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_axi_uart16550_reserved_0 || ORIG_REF_NAME==TimeCard_axi_uart16550_reserved_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_clk_wiz_0_0/TimeCard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_clk_wiz_0_0 || ORIG_REF_NAME==TimeCard_clk_wiz_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_clk_wiz_1_0/TimeCard_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_clk_wiz_1_0 || ORIG_REF_NAME==TimeCard_clk_wiz_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_clk_wiz_2_0/TimeCard_clk_wiz_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_clk_wiz_2_0 || ORIG_REF_NAME==TimeCard_clk_wiz_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_proc_sys_reset_0_0/TimeCard_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_proc_sys_reset_0_0 || ORIG_REF_NAME==TimeCard_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_proc_sys_reset_1_0/TimeCard_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_proc_sys_reset_1_0 || ORIG_REF_NAME==TimeCard_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_proc_sys_reset_2_0/TimeCard_proc_sys_reset_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_proc_sys_reset_2_0 || ORIG_REF_NAME==TimeCard_proc_sys_reset_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_util_ds_buf_0_0/TimeCard_util_ds_buf_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_util_ds_buf_0_0 || ORIG_REF_NAME==TimeCard_util_ds_buf_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_util_ds_buf_1_0/TimeCard_util_ds_buf_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_util_ds_buf_1_0 || ORIG_REF_NAME==TimeCard_util_ds_buf_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xlconstant_0_0/TimeCard_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xlconstant_0_0 || ORIG_REF_NAME==TimeCard_xlconstant_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xlconstant_1_0/TimeCard_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xlconstant_1_0 || ORIG_REF_NAME==TimeCard_xlconstant_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xlconstant_2_0/TimeCard_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xlconstant_2_0 || ORIG_REF_NAME==TimeCard_xlconstant_2_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xlconstant_4_0/TimeCard_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xlconstant_4_0 || ORIG_REF_NAME==TimeCard_xlconstant_4_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_xlconstant_6_0/TimeCard_xlconstant_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_xlconstant_6_0 || ORIG_REF_NAME==TimeCard_xlconstant_6_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_ds_0/TimeCard_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_ds_0 || ORIG_REF_NAME==TimeCard_auto_ds_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_pc_0/TimeCard_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_pc_0 || ORIG_REF_NAME==TimeCard_auto_pc_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_rs_0/TimeCard_auto_rs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_rs_0 || ORIG_REF_NAME==TimeCard_auto_rs_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_15/TimeCard_auto_cc_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_15 || ORIG_REF_NAME==TimeCard_auto_cc_15} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_0/TimeCard_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_0 || ORIG_REF_NAME==TimeCard_auto_cc_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_1/TimeCard_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_1 || ORIG_REF_NAME==TimeCard_auto_cc_1} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_2/TimeCard_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_2 || ORIG_REF_NAME==TimeCard_auto_cc_2} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_3/TimeCard_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_3 || ORIG_REF_NAME==TimeCard_auto_cc_3} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_4/TimeCard_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_4 || ORIG_REF_NAME==TimeCard_auto_cc_4} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_5/TimeCard_auto_cc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_5 || ORIG_REF_NAME==TimeCard_auto_cc_5} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_6/TimeCard_auto_cc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_6 || ORIG_REF_NAME==TimeCard_auto_cc_6} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_7/TimeCard_auto_cc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_7 || ORIG_REF_NAME==TimeCard_auto_cc_7} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_8/TimeCard_auto_cc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_8 || ORIG_REF_NAME==TimeCard_auto_cc_8} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_9/TimeCard_auto_cc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_9 || ORIG_REF_NAME==TimeCard_auto_cc_9} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_10/TimeCard_auto_cc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_10 || ORIG_REF_NAME==TimeCard_auto_cc_10} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_11/TimeCard_auto_cc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_11 || ORIG_REF_NAME==TimeCard_auto_cc_11} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_12/TimeCard_auto_cc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_12 || ORIG_REF_NAME==TimeCard_auto_cc_12} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_13/TimeCard_auto_cc_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_13 || ORIG_REF_NAME==TimeCard_auto_cc_13} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_auto_cc_14/TimeCard_auto_cc_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_auto_cc_14 || ORIG_REF_NAME==TimeCard_auto_cc_14} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_tier2_xbar_0_0/TimeCard_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_tier2_xbar_0_0 || ORIG_REF_NAME==TimeCard_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_tier2_xbar_1_0/TimeCard_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_tier2_xbar_1_0 || ORIG_REF_NAME==TimeCard_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/TimeCard/ip/TimeCard_tier2_xbar_2_0/TimeCard_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==TimeCard_tier2_xbar_2_0 || ORIG_REF_NAME==TimeCard_tier2_xbar_2_0} -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/TimeCard_ooc.xdc
