#!/bin/sh -f
# Vivado (TM) v2019.1 (64-bit)
# Filename: runme.sh
# Generated by Vivado on-demand to launch the synthesis run

# PATH setup (adjust if Vivado is installed in a different location)
if [ -z "$PATH" ]; then
  PATH=/tools/Xilinx/SDK/2019.1/bin:/tools/Xilinx/Vivado/2019.1/ids_lite/ISE/bin/lin64:/tools/Xilinx/Vivado/2019.1/ids_lite/ISE/lib/lin64:/tools/Xilinx/Vivado/2019.1/bin
else
  PATH=/tools/Xilinx/SDK/2019.1/bin:/tools/Xilinx/Vivado/2019.1/ids_lite/ISE/bin/lin64:/tools/Xilinx/Vivado/2019.1/ids_lite/ISE/lib/lin64:/tools/Xilinx/Vivado/2019.1/bin:$PATH
fi
export PATH

HD_LOG=runme.log
/bin/touch $HD_LOG

ISE_STEP=./ISEWrap.sh
EAStep(){
  $ISE_STEP $HD_LOG "$@"
}

EAStep vivado -log TimeCardTop.vds -m64 -product Vivado -mode batch -messageDb vivado.pb -notrace -source TimeCardTop.tcl