# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.srcs/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0.xci
# IP: The module: 'TimeCard_axi_uart16550_ext_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_axi_uart16550_ext_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_axi_uart16550_ext_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_axi_uart16550_ext_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.srcs/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0.xci
# IP: The module: 'TimeCard_axi_uart16550_ext_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_axi_uart16550_ext_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_axi_uart16550_ext_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/SHIWA/Documents/GitHub/QuantumFPGA/Implementation/Xilinx/TimeCard_Production/TimeCard/TimeCard.gen/sources_1/bd/TimeCard/ip/TimeCard_axi_uart16550_ext_0/TimeCard_axi_uart16550_ext_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'TimeCard_axi_uart16550_ext_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
